import { test } from 'node:test';
import assert from 'node:assert/strict';
import { score, walkBook, fundingPayments, round } from '../src/core/scorer';
import { fixtureSnapshot, defaultPolicy } from '../src/core/fixtures';
import { parseIntent, validateIntent } from '../src/core/parser';
import { runCampaign } from '../src/core/campaign';
import { canonical } from '../src/core/canonical';
const buy=()=>parseIntent('Buy 200 USDT of SOL, hold 24h');
test('fixture BUY selects Convert, retains all 13 paths and baseline',()=>{const c=score(buy(),fixtureSnapshot(),defaultPolicy);assert.equal(c.paths.length,13);assert.equal(c.winner,'P_CONVERT');assert.equal(c.paths[0].path_id,'P_SPOT_TAKER');assert.ok(c.paths[1].delta_vs_baseline!>0);});
test('book walk charges each displayed level and fails at insufficient depth',()=>{assert.equal(walkBook([[100,1],[102,2]],2),202);assert.equal(walkBook([[100,1]],2),null);assert.equal(walkBook([[100,1]],0),0);});
test('stale snapshots fail closed across all routes',()=>{const s=fixtureSnapshot();s.now+=16000;const c=score(buy(),s,defaultPolicy);assert.equal(c.winner,null);assert.ok(c.paths.every(p=>!p.legal&&p.reason_code==='STALE'));});
test('expired Convert loses eligibility without an invented replacement',()=>{const s=fixtureSnapshot();s.convert!.expires_at=s.now;const c=score(buy(),s,defaultPolicy);assert.equal(c.paths[1].reason_code,'QUOTE_EXPIRED');assert.equal(c.winner,'P_SPOT_TAKER');});
test('missing Convert remains visible',()=>{const s=fixtureSnapshot();s.convert=null;const c=score(buy(),s,defaultPolicy);assert.equal(c.paths[1].reason_code,'CONVERT_UNAVAILABLE');});
test('wrong-pocket quote produces explicit transfer and balance-wait legs',()=>{const c=score(buy(),fixtureSnapshot('SOL','USDM'),defaultPolicy);assert.equal(c.paths[0].reason_code,'WRONG_POCKET');assert.equal(c.winner,'P_XFER_SPOT_THEN_TAKER');assert.deepEqual(c.paths.find(p=>p.path_id===c.winner)!.legs,['USD-M → Spot','Wait for balance','Spot market order']);});
test('missing transfer blocks wrong-pocket BUY',()=>{const s=fixtureSnapshot('SOL','USDM');s.transfer_available=false;assert.equal(score(buy(),s,defaultPolicy).winner,null);});
test('SELL picks the higher net proceeds and cannot sell unowned base',()=>{const i=parseIntent('Sell 100 USDT of ETH');const s=fixtureSnapshot('ETH');const c=score(i,s,defaultPolicy);assert.equal(c.winner,'P_CONVERT');assert.ok(c.paths[1].all_in!>c.paths[0].all_in!);s.wallets[0].base=0;assert.equal(score(i,s,defaultPolicy).winner,null);});
test('funding counts next event only when inside horizon',()=>{const s=fixtureSnapshot();assert.equal(fundingPayments(s,0),0);assert.equal(fundingPayments(s,14399),0);assert.equal(fundingPayments(s,14400),1);assert.equal(fundingPayments(s,86400),3);});
test('zero quantity, dual amounts, and ambiguous intents clarify',()=>{assert.throws(()=>parseIntent('do something with SOL'));assert.throws(()=>parseIntent('Buy 0 USDT of SOL'));assert.throws(()=>validateIntent({...buy(),qty_base:1}));assert.throws(()=>parseIntent('Buy 200 USDT of SOL with 10x leverage'));});
test('dust below lot size is ineligible and no nonfinite prices leak',()=>{const i=buy();i.notional_quote=0.0000001;const c=score(i,fixtureSnapshot(),defaultPolicy);assert.equal(c.winner,null);assert.ok(c.paths.every(p=>p.reason_code==='LOT_SIZE'));});
test('symbol and notional policies cannot be bypassed',()=>{const i=buy();i.notional_quote=1001;assert.equal(score(i,fixtureSnapshot(),defaultPolicy).winner,null);assert.equal(score(buy(),fixtureSnapshot('ETH'),defaultPolicy).winner,null);});
test('passive prices are not treated as guaranteed fills',()=>{const c=score(buy(),fixtureSnapshot(),defaultPolicy);assert.equal(c.paths.find(p=>p.path_id==='P_SPOT_LIMIT')?.reason_code,'FILL_NOT_GUARANTEED');});
test('bankers rounding resolves positive and negative ties',()=>{assert.equal(round(1.125,2),1.12);assert.equal(round(1.135,2),1.14);assert.equal(round(-1.125,2),-1.12);});
test('scorer is deterministic, pure, and canonical keys are stable',()=>{const s=fixtureSnapshot(),i=buy(),before=JSON.stringify(s);assert.deepEqual(score(i,s,defaultPolicy),score(i,s,defaultPolicy));assert.equal(JSON.stringify(s),before);assert.equal(canonical({b:2,a:1}),canonical({a:1,b:2}));});
test('campaign includes 120 attempts and all six ablations',()=>{const c=runCampaign();assert.equal(c.attempts,120);assert.equal(c.summary.length,6);assert.ok(c.rows.every(r=>r.results.length===6));assert.ok(c.summary.every(s=>s.completed+s.blocked===120));});
