'use client';
import Link from 'next/link';
import { useEffect, useRef, useState } from 'react';
import { Icon } from './icon';
import { fixtureSnapshot, defaultPolicy } from '@/core/fixtures';
import { parseIntent } from '@/core/parser';
import { score } from '@/core/scorer';
import { runCampaign } from '@/core/campaign';
import { validatePolicy } from '@/core/policy';
import type { Path, Policy, Receipt, Scorecard } from '@/core/types';

const example='Buy 200 USDT of SOL, hold 24h';
const money=(n:number|null,digits=2)=>n===null?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:digits,maximumFractionDigits:digits}).format(n);
const nav=[['overview','grid','Overview','/'],['wallets','wallet','Wallets','/wallets'],['receipts','receipt','Receipts','/receipts'],['campaign','chart','Campaign','/campaign'],['proof','shield','Proof explorer','/proof']];
const reason=(s:string)=>s.toLowerCase().replaceAll('_',' ');
function Badge({children,tone='neutral'}:{children:React.ReactNode;tone?:string}){return <span className={`badge ${tone}`}>{children}</span>}
function Coin({symbol='SOL',small=false}:{symbol?:string;small?:boolean}){return <span className={`coin ${symbol.toLowerCase()} ${small?'small':''}`}>{symbol==='SOL'?<span className="sol-lines"><i/><i/><i/></span>:symbol==='BTC'?'₿':symbol==='ETH'?'♦':symbol==='BNB'?'◇':symbol==='USDT'?'₮':'×'}</span>}
function DownloadButton({data,name,label='Export JSON'}:{data:unknown;name:string;label?:string}){return <button className="button secondary" onClick={()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);}}><Icon name="download" size={16}/>{label}</button>}

export function Dashboard({page}:{page:string}){
  const [hydrated,setHydrated]=useState(false);
  const [text,setText]=useState(example);
  const [policy,setPolicy]=useState<Policy>(defaultPolicy);
  const [pocket,setPocket]=useState<'SPOT'|'USDM'>('SPOT');
  const [card,setCard]=useState<Scorecard>(()=>score(parseIntent(example),fixtureSnapshot(),defaultPolicy));
  const [error,setError]=useState('');const [notice,setNotice]=useState('');
  const [scoring,setScoring]=useState(false);const [executing,setExecuting]=useState(false);
  const [stopped,setStopped]=useState(false);const [allPaths,setAllPaths]=useState(false);
  const [modal,setModal]=useState<'connection'|'execute'|null>(null);
  const [receipts,setReceipts]=useState<Receipt[]>([]);const [selected,setSelected]=useState<Receipt|null>(null);
  const [verify,setVerify]=useState('');const [query,setQuery]=useState('');
  const [campaign,setCampaign]=useState<ReturnType<typeof runCampaign>|null>(null);
  const [connection,setConnection]=useState<{status:string;families:{family:string;reason:string}[]}|null>(null);
  const inputRef=useRef<HTMLTextAreaElement>(null);
  const winner=card.paths.find(p=>p.path_id===card.winner);
  const [scoredText,setScoredText]=useState(example);
  const pendingChanges=text!==scoredText||pocket!==(card.snapshot.wallets[0].quote>100?'SPOT':'USDM')||JSON.stringify(policy)!==JSON.stringify(card.policy);
  useEffect(()=>{const id=requestAnimationFrame(()=>setHydrated(true));return()=>cancelAnimationFrame(id);},[]);
  useEffect(()=>{let mounted=true;fetch('/api/receipts').then(r=>r.json()).then(data=>{if(mounted&&Array.isArray(data))setReceipts(data);}).catch(()=>{if(mounted)setError('Could not load saved receipts.');});return ()=>{mounted=false;};},[]);
  useEffect(()=>{let mounted=true;fetch('/api/control').then(r=>r.json()).then(data=>{if(mounted)setStopped(data.stopped);}).catch(()=>{});Promise.resolve().then(()=>{try{const saved=sessionStorage.getItem('pathwise-policy');if(saved&&mounted){const p=validatePolicy(JSON.parse(saved));setPolicy(p);setCard(score(parseIntent(example),fixtureSnapshot(),p));}}catch{sessionStorage.removeItem('pathwise-policy');}});return()=>{mounted=false;};},[]);
  useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),4500);return()=>clearTimeout(timer);},[notice]);
  useEffect(()=>{if(!modal&&!selected)return;const handler=(e:KeyboardEvent)=>{if(e.key==='Escape'){setModal(null);setSelected(null);}};document.addEventListener('keydown',handler);return()=>document.removeEventListener('keydown',handler);},[modal,selected]);
  async function scoreIntent(overrideText?: string, overridePocket?: 'SPOT'|'USDM'){
    const targetText = overrideText ?? text;
    const targetPocket = overridePocket ?? pocket;
    setError('');setScoring(true);
    try{
      const intent=parseIntent(targetText);
      const next=score(intent,fixtureSnapshot(intent.base,targetPocket),policy);
      await new Promise(r=>setTimeout(r,200));
      setCard(next);
      setScoredText(targetText);
      setNotice(`Scored ${intent.side} ${intent.base} via ${targetPocket === 'SPOT' ? 'Spot' : 'USD-M'} pocket.`);
      if(!next.winner)setError('No eligible path for this intent. Review the reasons in the path table.');
    }
    catch(e){setError((e as Error).message);}finally{setScoring(false);}
  }
  function applyExample(val: string){
    setText(val);
    scoreIntent(val);
  }
  async function execute(){
    if(stopped||pendingChanges)return;
    setExecuting(true);setError('');
    try{const response=await fetch('/api/receipts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:scoredText,pocket,mode:policy.mode,policy})});const result=await response.json();if(!response.ok)throw new Error(result.error);setReceipts(r=>[result,...r]);setModal(null);setSelected(result);setVerify('');}
    catch(e){setError((e as Error).message);setModal(null);}finally{setExecuting(false);}
  }
  async function checkConnection(){setModal('connection');try{const r=await fetch('/api/connection');setConnection(await r.json());}catch{setError('Unable to read connection status.');}}
  async function toggleStop(){try{const r=await fetch('/api/control',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({stopped:!stopped})});if(!r.ok)throw new Error('Could not update emergency stop.');const data=await r.json();setStopped(data.stopped);setNotice(data.stopped?'Emergency stop enabled. New fixture runs are paused.':'Fixture runs resumed.');}catch(e){setError((e as Error).message);}}
  async function verifySelected(receipt:Receipt){setVerify('VERIFYING');try{const r=await fetch('/api/verify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({receipt_id:receipt.receipt_id})});const data=await r.json();setVerify(data.status??'ERROR');}catch{setVerify('ERROR');}}
  const pageTitle:Record<string,string>={overview:'Overview',wallets:'Wallet map',receipts:'Receipts',campaign:'Campaign',proof:'Proof explorer',policy:'Execution policy'};
  const total=card.snapshot.wallets.reduce((sum,w)=>sum+w.quote,0);
  return <div className="app-shell" data-hydrated={hydrated?'true':'false'}>
    <aside className="sidebar">
      <Link href="/" className="brand"><span className="brand-mark"><Icon name="route" size={25}/></span>pathwise<span className="brand-period">.</span></Link>
      <button className="workspace-picker" onClick={checkConnection}><span className="workspace-avatar">D</span><span><strong>Divine’s workspace</strong><small>Personal workspace</small></span><Icon name="down" size={15}/></button>
      <div className="nav-label">WORKSPACE</div>
      <nav>{nav.map(([id,icon,label,href])=><Link key={id} href={href} className={`nav-link ${page===id?'active':''}`}><Icon name={icon} size={19}/><span>{label}</span>{id==='overview'&&<span className="nav-active-dot"/>}{id==='receipts'&&receipts.length>0&&<span className="nav-count">{receipts.length}</span>}</Link>)}</nav>
      <div className="nav-label second">MANAGE</div>
      <Link href="/policy" className={`nav-link ${page==='policy'?'active':''}`}><Icon name="settings" size={19}/><span>Policy & limits</span></Link>
      <button className="nav-link" onClick={checkConnection}><Icon name="link" size={19}/><span>Connections</span><span className="connection-dot"/></button>
      <div className="sidebar-bottom"><div className="agent-card"><div className="agent-heading"><span className="binance-symbol">❖</span> Built for Binance</div><p>Your intent. The best path.<br/>Every cent accounted for.</p><span>AGENT OS <span className="tiny-dot"/> TRACK A</span></div>
      <button className={`emergency ${stopped?'is-stopped':''}`} onClick={toggleStop} aria-label={stopped?'Resume workspace':'Emergency stop'}><Icon name="stop" size={16}/>{stopped?'Resume workspace':'Emergency stop'}</button>
      <div className="profile"><span className="profile-avatar">DA</span><div><strong>Divine</strong><small>Workspace owner</small></div><Icon name="down" size={16}/></div></div>
    </aside>
    <div className="workspace-main">
      <header className="topbar"><div className="breadcrumb">Workspace <Icon name="chevron" size={13}/><span>{pageTitle[page]}</span></div><div className="topbar-actions"><span className="environment"><span/> Fixture environment</span><span className="topbar-divider"/><button className="connection-button" onClick={checkConnection}><span className="binance-symbol">❖</span>Connect Binance<Icon name="external" size={14}/></button><button className="avatar-button" aria-label="Workspace connection details" onClick={checkConnection}>D</button></div></header>
      <main>
        <div className="page-heading"><div><div className="eyebrow">YOUR EXECUTION WORKSPACE</div><h1>{page==='overview'?'Every path. Every cent.':pageTitle[page]}</h1><p>{page==='overview'?'Tell us the intent. We’ll find the most efficient way to make it happen.':page==='wallets'?'The right assets, in the right wallet, before the first order.':page==='receipts'?'An immutable record of the inputs, the route, and the math.':page==='campaign'?'Same intents. Same inputs. Every result, including the losses.':page==='proof'?'Don’t take our word for it. Recompute every route.':'Clear boundaries for every intent and every execution.'}</p></div><div className="heading-actions">{page==='overview'?<button className="button secondary" onClick={()=>{setText('');inputRef.current?.focus();}}><Icon name="plus" size={17}/>New intent</button>:<Link href="/" className="button secondary"><Icon name="plus" size={17}/>Create intent</Link>}</div></div>
        <div className="fixture-banner"><span className="fixture-icon"><Icon name="info" size={17}/></span><span><strong>You’re in the fixture workspace.</strong> Explore routing with synthetic inputs. No real funds move.</span><button onClick={checkConnection}>Connection details <Icon name="arrow" size={15}/></button></div>
        {stopped&&<div className="error-box"><Icon name="stop" size={18}/>Emergency stop is active. New runs are paused.</div>}
        {error&&<div className="error-box" role="alert"><Icon name="info" size={18}/>{error}<button aria-label="Dismiss error" onClick={()=>setError('')}><Icon name="close" size={16}/></button></div>}
        {page==='overview'&&<>
          <section className="stats-grid"><div className="stat-card"><div className="stat-label">Estimated route advantage <Icon name="route" size={17}/></div><div className="stat-value mint">{winner?.delta_vs_baseline!=null?(winner.delta_vs_baseline/100).toFixed(2):'—'}<span>USDT</span><svg className="sparkline" viewBox="0 0 105 36"><path d="M1 30 14 27 25 29 38 19 51 22 62 13 76 16 88 6 103 3"/></svg></div><div className="stat-foot"><Badge tone="green">THIS INTENT</Badge><span>vs. taker Spot · fixture estimate</span></div></div>
          <div className="stat-card"><div className="stat-label">Paths considered <Icon name="route" size={17}/></div><div className="stat-value">{card.paths.length}<span>routes</span></div><div className="stat-foot"><span className="green-dot"/><span>{card.paths.filter(p=>p.legal).length} eligible</span><span className="dot-separator">·</span><span>All blocked paths stay visible</span></div></div>
          <div className="stat-card"><div className="stat-label">Fixture receipts <Icon name="receipt" size={17}/></div><div className="stat-value">{receipts.length.toString().padStart(2,'0')}<span>recorded</span></div><div className="stat-foot"><Icon name="shield" size={14}/><span>Deterministic. Exportable. Verifiable.</span></div></div></section>
          <div className="overview-grid"><div className="left-stack">
            <section className="panel intent-panel"><div className="section-title"><div><span className="step-number">01</span><h2>What’s your next move?</h2></div><Badge tone="purple"><span className="purple-dot"/>{policy.mode}</Badge></div>
              <div className="intent-field"><textarea ref={inputRef} aria-label="Trading intent" value={text} onChange={e=>setText(e.target.value)} placeholder="Buy 200 USDT of SOL, hold 24h" spellCheck={false}/><div className="intent-field-footer"><span><Icon name="code" size={14}/>Natural language or JSON</span><span>↵ <span className="muted">to a better path</span></span></div></div>
              <div className="intent-examples"><span>Try an intent</span>{[['Buy SOL',example],['Sell ETH','Sell 100 USDT of ETH'],['Rotate USDT','Rotate 200 USDT of SOL']].map(([label,value])=><button key={label} onClick={()=>applyExample(value)}>{label}<Icon name="arrow" size={12}/></button>)}</div>
              <div className="intent-controls"><div className="policy-chips"><span><Icon name="shield" size={13}/>1× leverage</span><span>Max {money(policy.max_notional_usdt,0)}</span><span>{policy.max_slippage_bps} bps slippage</span></div><button className="button primary" onClick={()=>scoreIntent()} disabled={scoring||stopped||!text.trim()}>{scoring?<span className="spinner"/>:<Icon name="route" size={17}/>} {scoring?'Scoring paths…':'Find best path'}<Icon name="arrow" size={16}/></button></div>
            </section>
            <section className="panel path-panel"><div className="section-title"><div><span className="step-number">02</span><h2>The path comparison</h2><Badge>{card.intent.base}/USDT</Badge></div><span className="small-meta"><span className="green-dot"/>{pendingChanges?'Previous score':'Fixture snapshot'}</span></div><div className="path-subheading"><span>All-in cost. Same intent. No hidden terms.</span><button className="text-button" onClick={()=>setAllPaths(v=>!v)}>{allPaths?'Show top routes':`All ${card.paths.length} paths`}<Icon name="down" size={14}/></button></div>
              <div className="table-scroll"><table className="path-table"><thead><tr><th>Execution path</th><th>Price</th><th>Fees + costs</th><th>{card.intent.side==='SELL'?'Net proceeds':'All-in'}</th><th>vs. Spot</th></tr></thead><tbody>{(allPaths?card.paths:card.paths.slice(0,5)).map(p=><PathRow key={p.path_id} path={p} winner={p.path_id===card.winner}/>)}</tbody></table></div>
              <div className="table-footer"><Icon name="shield" size={14}/><span>Deterministic scoring · fees, book impact & funding included</span><span className="mono">FIXTURE / 12:00:00 UTC</span></div>
            </section>
          </div><div className="right-stack">
            <section className="panel wallet-summary"><div className="section-title"><div><Icon name="wallet" size={18}/><h2>Your wallet map</h2></div><Link href="/wallets" aria-label="Open wallet map"><Icon name="external" size={16}/></Link></div><div className="wallet-total"><span>Available quote · fixture</span><strong>{money(total)}<small>USDT</small></strong></div><div className="wallet-allocation"><span style={{width:`${card.snapshot.wallets[0].quote/total*100}%`}}/><span/></div><div className="wallet-mini-list">{card.snapshot.wallets.slice(0,3).map((w,i)=><div key={w.id}><span><i className={`wallet-dot dot-${i}`}/>{w.name}</span><strong>{money(w.quote)}</strong></div>)}</div><div className="wallet-scenario"><label htmlFor="pocket">Starting wallet</label><select id="pocket" value={pocket} onChange={e=>{const next=e.target.value as 'SPOT'|'USDM';setPocket(next);scoreIntent(text,next);}}><option value="SPOT">USDT on Spot</option><option value="USDM">USDT on USD-M</option></select></div><div className="small-note"><Icon name="info" size={13}/>Transfers are included in route scoring.</div></section>
            <section className="winner-panel"><div className="winner-heading"><span className="winner-star">✦</span>THE WINNING PATH<Badge tone="green">FIXTURE</Badge></div><div className="winner-name"><span className="winner-icon"><Icon name="route" size={25}/></span><div><h2>{winner?.label??'No eligible path'}</h2><span>{winner?`${winner.legs.length} ${winner.legs.length===1?'step':'steps'} · deterministic selection`:'Review blocked reasons'}</span></div></div><div className="winner-saving"><span>Estimated advantage vs. Spot</span><strong>{winner?.delta_vs_baseline!=null?`${winner.delta_vs_baseline.toFixed(2)}¢`:'—'}<Icon name="arrow" size={24}/></strong></div><p>{winner?'The lowest eligible cost in this fixture, after all scored terms. No live savings claimed.':'The scorer fails closed when no route satisfies your constraints.'}</p><button className="button primary full" disabled={!winner||stopped||executing} onClick={()=>pendingChanges?scoreIntent():policy.mode==='AUTO'?execute():setModal('execute')}>{pendingChanges?'Rescore your changes':policy.mode==='AUTO'?'Run fixture':'Review fixture run'}<Icon name="arrow" size={17}/></button><div className="winner-disclaimer"><Icon name="shield" size={13}/>No real orders. A verifiable fixture receipt.</div></section>
          </div></div>
          <section className="panel recent-panel"><div className="section-title"><div><h2>Recent receipts</h2><Badge>{receipts.length}</Badge></div><Link href="/receipts" className="text-button">View all receipts<Icon name="arrow" size={14}/></Link></div>{receipts.length?<ReceiptTable receipts={receipts.slice(0,3)} onSelect={r=>{setSelected(r);setVerify('');}}/>:<div className="inline-empty"><span className="empty-icon"><Icon name="receipt" size={24}/></span><div><strong>The proof comes after the path.</strong><p>Run your first fixture to save an inspectable, verifiable receipt.</p></div><span className="empty-dashes">— — —</span></div>}</section>
        </>}
        {page==='wallets'&&<><div className="section-toolbar"><div><h2>Agentic wallet topology</h2><p>Fixture balances. Main-account transfers and withdrawals are never bound.</p></div><select aria-label="Wallet scenario" value={pocket} onChange={e=>{const next=e.target.value as 'SPOT'|'USDM';setPocket(next);setCard(score(card.intent,fixtureSnapshot(card.intent.base,next),policy));}}><option value="SPOT">USDT starts on Spot</option><option value="USDM">USDT starts on USD-M</option></select></div><div className="wallet-grid">{card.snapshot.wallets.map((w,i)=><section className="panel wallet-detail" key={w.id}><div className="section-title"><Icon name="wallet" size={23}/><Badge tone={w.status==='BLOCKED'?'amber':'green'}>{w.status==='BLOCKED'?'SCOPE BLOCKED':'FIXTURE'}</Badge></div><h2>{w.name}</h2><strong className="wallet-balance">{w.status==='BLOCKED'?'—':money(w.quote)}</strong><span className="muted">USDT available</span><div className="wallet-detail-footer"><i className={`wallet-dot dot-${i%3}`}/>{w.status==='BLOCKED'?'No balance access granted':`${w.base.toFixed(4)} ${card.intent.base} · fixture balance`}</div></section>)}</div><section className="panel seam-panel"><h2>Wallet seams are execution legs.</h2><p>A transfer is scored as part of the route, with an explicit balance wait before placing an order.</p><div className="seam-diagram"><span><Icon name="wallet"/>Spot wallet</span><div><small>Exact need + fee buffer</small><Icon name="arrow" size={30}/><small>WAIT_BALANCE</small></div><span><Icon name="wallet"/>USD-M Futures</span></div><div className="small-note"><Icon name="info" size={15}/>Binance MCP is connected, but this app&apos;s backend is not yet wired to execute transfers. No funds are moved from this view.</div></section></>}
        {(page==='receipts'||page==='proof')&&<><div className="section-toolbar"><div><h2>{page==='proof'?'Independently verifiable. By design.':'Your execution ledger'}</h2><p>{page==='proof'?'Select a receipt to rerun the scorer against its original inputs.':'Fixture records are kept separate from paper and live results.'}</p></div><div className="search-field"><Icon name="search" size={16}/><input aria-label="Search receipts" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search asset or receipt ID…"/></div></div><section className="panel">{receipts.length?<ReceiptTable receipts={receipts.filter(r=>`${r.receipt_id} ${r.scorecard.intent.base}`.toLowerCase().includes(query.toLowerCase()))} onSelect={r=>{setSelected(r);setVerify('');}}/>:<div className="large-empty"><span className="empty-icon"><Icon name={page==='proof'?'shield':'receipt'} size={32}/></span><h2>{page==='proof'?'Proof starts with a receipt.':'A clean slate. An open ledger.'}</h2><p>Score an intent and run a fixture from the overview.<br/>Its recorded inputs and deterministic result will appear here.</p><Link href="/" className="button primary">Create your first receipt<Icon name="arrow" size={16}/></Link></div>}</section><div className="proof-features">{[['code','Recorded inputs','Exact snapshot and policy. No future data.'],['refresh','Local recompute','The same deterministic function, run again.'],['shield','Content hashes','SHA-256 over canonical inputs and scores.']].map(([icon,title,desc])=><div key={title}><Icon name={icon} size={22}/><h3>{title}</h3><p>{desc}</p></div>)}</div></>}
        {page==='campaign'&&<><div className="section-toolbar"><div><h2>The frozen comparison set</h2><p>5 symbols × 3 sizes × 2 sides × 2 wallets × 2 horizons = 120 attempts.</p></div><button className="button primary" onClick={()=>{setCampaign(runCampaign());setNotice('120 fixture attempts evaluated across six variants.');}}><Icon name="chart" size={17}/>{campaign?'Rerun fixture campaign':'Run fixture campaign'}</button></div><div className="campaign-config">{[['Assets','BTC · ETH · SOL · BNB · XRP'],['Notionals','25 · 100 · 200 USDT'],['Hold horizons','0 hours · 24 hours'],['Environment','Synthetic fixtures only']].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>{campaign?<><section className="panel campaign-results"><div className="section-title"><h2>Median estimated cents per $1,000</h2><Badge tone="amber">FIXTURE · NOT REALIZED</Badge></div><div className="ablation-chart">{campaign.summary.map((v,i)=><div className="ablation-row" key={v.variant}><span>{v.variant.replaceAll('_',' ')}</span><div><i className={i===0?'full-bar':''} style={{width:`${Math.max(2,v.median_cents_per_1000/Math.max(1,...campaign.summary.map(x=>x.median_cents_per_1000))*100)}%`}}/></div><strong>{v.median_cents_per_1000.toFixed(2)}¢</strong><small>{v.completed}/{campaign.attempts} eligible</small></div>)}</div><p className="small-note">All variants are evaluated against the full cost model. “Random” uses a reproducible fixture index. This does not prove a live routing advantage.</p><DownloadButton data={campaign} name="pathwise-fixture-campaign.json" label="Export all attempts"/></section><section className="panel campaign-results"><h2>Attempts, including blocked runs</h2><div className="table-scroll campaign-table"><table><thead><tr><th>Asset</th><th>Intent</th><th>Wallet</th><th>Horizon</th><th>Winner</th><th>Delta</th></tr></thead><tbody>{campaign.rows.map((r,i)=><tr key={i}><td>{r.base}</td><td>{r.side} {r.size}</td><td>{r.pocket}</td><td>{r.horizon/3600}h</td><td>{r.results[0].winner??'BLOCKED'}</td><td>{r.results[0].delta?.toFixed(2)??'—'}¢</td></tr>)}</tbody></table></div></section></>:<section className="panel large-empty"><span className="empty-icon"><Icon name="chart" size={32}/></span><h2>No selective screenshots. The whole set.</h2><p>Run the frozen fixture campaign to compare six scoring variants.<br/>Every attempt is included in the downloadable result.</p></section>}</>}
        {page==='policy'&&<section className="panel policy-panel"><div className="section-title"><div><Icon name="shield"/><h2>Default execution policy</h2></div><Badge tone="green">PAPER ONLY</Badge></div><p className="muted">Policy changes apply to this browser session. Live execution is unavailable.</p><div className="policy-form">{[['max_notional_usdt','Maximum per intent (USDT)'],['max_daily_usdt','Daily notional cap (reserved; execution blocked)'],['max_slippage_bps','Maximum slippage (bps)'],['max_funding_bps','Maximum funding (bps)']].map(([key,label])=><label key={key}>{label}<input type="number" min="0" value={policy[key as keyof Policy] as number} onChange={e=>setPolicy(p=>({...p,[key]:Math.max(0,Number(e.target.value))}))}/></label>)}<label>Approval mode<select value={policy.mode} onChange={e=>setPolicy(p=>({...p,mode:e.target.value as 'APPROVE'|'AUTO'}))}><option>APPROVE</option><option>AUTO</option></select></label><label>Maximum leverage<input value="1× — no inferred leverage" disabled/></label></div><div className="policy-allowlist"><h3>Symbol allowlist</h3>{defaultPolicy.allowlist.map(base=><button key={base} className={`asset-toggle ${policy.allowlist.includes(base)?'selected':''}`} onClick={()=>setPolicy(p=>({...p,allowlist:p.allowlist.includes(base)?p.allowlist.filter(b=>b!==base):[...p.allowlist,base]}))}><Coin symbol={base} small/>{base}{policy.allowlist.includes(base)&&<Icon name="check" size={14}/>}</button>)}</div><button className="button primary" onClick={()=>{sessionStorage.setItem('pathwise-policy',JSON.stringify(policy));setNotice('Policy saved for this session. New intents use these limits.');}}>Save policy<Icon name="check" size={16}/></button><p className="small-note">No withdrawal capability. No main-account funding. No live order adapter bound.</p></section>}
        <footer className="page-footer"><span><span className="footer-mark">↱</span> pathwise <span className="dot-separator">·</span> Intent in. Proof out.</span><span>Deterministic by design.<span className="dot-separator">·</span><Link href="/proof">Explore the proof<Icon name="external" size={12}/></Link></span></footer>
      </main>
    </div>
    {notice&&<div className="toast" role="status"><Icon name="check" size={17}/>{notice}</div>}
    {modal==='connection'&&<Modal title="Binance Agent OS" onClose={()=>setModal(null)}><div className="connection-status"><span className="binance-symbol">❖</span><div><h3>Binance MCP is connected</h3><p>OAuth authenticated. 73 tools cataloged. Fixture workspace remains the execution path.</p></div><Badge tone="green">CONNECTED</Badge></div><p className="modal-description">The MCP client holds an authenticated session with the official Binance Agent MCP endpoint and its full tool catalog. This app&apos;s backend does not yet call these tools at runtime, so the dashboard below still runs on fixtures — see GATES.md for the exact status.</p><div className="endpoint mono">https://agent.binance.com/mcp/agentic</div><div className="scope-list">{(connection?.families??['market','balance','convert','transfer','spot_order','futures_order'].map(family=>({family,reason:'MCP_CONNECTION_FAILED'}))).map(f=><div key={f.family}><span>{reason(f.family)}</span><Badge tone={f.reason.startsWith('LIVE')?'green':'amber'}>{f.reason}</Badge></div>)}</div><a className="button primary full" href="https://www.binance.com/en/support/faq/detail/7a6e676e36fb455d96478932cb12d9f3" target="_blank" rel="noreferrer">Read Binance connection guide<Icon name="external" size={16}/></a><p className="small-note">No API keys are requested or stored in this workspace.</p></Modal>}
    {modal==='execute'&&winner&&<Modal title="Review fixture run" onClose={()=>!executing&&setModal(null)}><Badge tone="amber">SYNTHETIC INPUTS · NO REAL FUNDS</Badge><h3 className="review-title">{card.intent.side} {card.intent.notional_quote??card.intent.qty_base} {card.intent.notional_quote?'USDT of ':''}{card.intent.base}</h3><p className="modal-description">The scorer selected <strong>{winner.label}</strong>. This run saves the plan and its inputs to the append-only fixture ledger.</p><div className="execution-timeline">{['Observe fixture snapshot','Enumerate all 13 paths',...winner.legs,'Write verifiable receipt'].map((leg,i)=><div key={i}><span>{i+1}</span><div><strong>{leg}</strong><small>{i<2?'SCORED':'SIMULATED — no external action'}</small></div></div>)}</div><div className="review-total"><span>Planned all-in</span><strong>{money(winner.all_in,4)}</strong></div><button className="button primary full" disabled={executing||stopped} onClick={execute}>{executing?<span className="spinner"/>:<Icon name="check" size={17}/>} {executing?'Writing receipt…':'Approve fixture run'}</button></Modal>}
    {selected&&<Modal title="The execution receipt" wide onClose={()=>setSelected(null)}><div className="receipt-modal-heading"><Badge tone="purple">FIXTURE</Badge><span className="mono">{selected.receipt_id.slice(0,8)}</span><Badge tone="green">RECORDED</Badge></div><h3 className="review-title">{selected.scorecard.intent.side} {selected.scorecard.intent.base} <span className="muted">via {selected.scorecard.paths.find(p=>p.path_id===selected.winner)?.label}</span></h3><div className="receipt-numbers"><div><span>Planned all-in</span><strong>{money(selected.planned_all_in,4)}</strong></div><div><span>Estimated delta vs. Spot</span><strong className="mint">{selected.delta_vs_baseline_planned?.toFixed(2)??'—'}¢</strong></div><div><span>Realized all-in</span><strong>—</strong></div></div><div className="small-note"><Icon name="info" size={16}/>No official fills. Fixture estimates are excluded from live and paper totals.</div><div className="hash-block"><span>SHA-256 · canonical inputs</span><code>{selected.inputs_hash}</code></div><div className="receipt-actions"><button className="button primary" onClick={()=>verifySelected(selected)} disabled={verify==='VERIFYING'}><Icon name="refresh" size={16}/>{verify==='VERIFYING'?'Recomputing…':'Recompute & verify'}</button><DownloadButton data={selected} name={`pathwise-${selected.receipt_id}.json`}/><button className="button secondary" onClick={async()=>{try{await navigator.clipboard.writeText(JSON.stringify(selected,null,2));setNotice('Receipt JSON copied.');}catch{setNotice('Clipboard unavailable. Export JSON instead.');}}}><Icon name="copy" size={16}/>Copy JSON</button></div>{verify&&<div className={`verify-result ${verify==='MATCH'?'match':''}`} role="status"><Icon name={verify==='MATCH'?'check':'info'} size={19}/><strong>{verify}</strong><span>{verify==='MATCH'?'Inputs, score hash, and winner match the recorded result.':verify==='DRIFT'?'Recorded data differs from the recomputed result.':'Checking the saved record…'}</span></div>}<details className="raw-json"><summary>Inspect recorded inputs & path scores</summary><pre>{JSON.stringify(selected,null,2)}</pre></details><div className="cli-command"><Icon name="code" size={16}/><code>{selected.verify_command}</code></div></Modal>}
  </div>;
}
function PathRow({path:p,winner}:{path:Path;winner:boolean}){const costs=p.spread_cost+p.impact_cost+p.fee_cost+p.convert_premium+p.funding_cost;return <tr className={`${winner?'winner-row':''} ${!p.legal?'ineligible-row':''}`}><td><div className="path-name"><span className={`path-icon ${p.venue==='Convert'?'convert-icon':p.venue.includes('USD')?'futures-icon':''}`}><Icon name={p.venue==='Convert'?'refresh':p.venue.includes('USD')?'route':'chart'} size={17}/></span><div><strong>{p.label}{winner&&<span className="winner-tag"><Icon name="check" size={10}/>BEST</span>}</strong><small>{p.path_id==='P_SPOT_TAKER'&&p.legal?'Baseline · market order':p.legal?p.description:reason(p.reason_code)}</small></div></div></td><td>{money(p.price,2)}</td><td><span title={`Spread ${p.spread_cost}; impact ${p.impact_cost}; fee ${p.fee_cost}; Convert ${p.convert_premium}; funding ${p.funding_cost}; dust ${p.dust_cost}`}>{p.all_in===null?'—':money(costs,4)}</span></td><td className="all-in-value">{money(p.all_in,4)}</td><td>{p.path_id==='P_SPOT_TAKER'?<span className="baseline-label">BASELINE</span>:p.legal&&p.delta_vs_baseline!==null?<span className={p.delta_vs_baseline>0?'delta-positive':'muted'}>{p.delta_vs_baseline>0?'−':'+'}{Math.abs(p.delta_vs_baseline).toFixed(2)}¢</span>:<span className="blocked-label">Unavailable</span>}</td></tr>}
function ReceiptTable({receipts,onSelect}:{receipts:Receipt[];onSelect:(r:Receipt)=>void}){return <div className="table-scroll"><table className="receipt-table"><thead><tr><th>Intent</th><th>Route</th><th>Estimated advantage</th><th>Environment</th><th>Receipt</th><th/></tr></thead><tbody>{receipts.map(r=><tr key={r.receipt_id}><td><div className="receipt-intent"><Coin symbol={r.scorecard.intent.base} small/><div><strong>{r.scorecard.intent.side} {r.scorecard.intent.base}</strong><small>{money(r.scorecard.intent.notional_quote??null)} notional</small></div></div></td><td>{r.scorecard.paths.find(p=>p.path_id===r.winner)?.label}</td><td className="delta-positive">{r.delta_vs_baseline_planned?.toFixed(2)??'—'}¢</td><td><Badge>FIXTURE</Badge></td><td className="mono">{r.receipt_id.slice(0,8)}</td><td><button className="icon-button" onClick={()=>onSelect(r)} aria-label={`Open receipt ${r.receipt_id}`}><Icon name="arrow" size={18}/></button></td></tr>)}{!receipts.length&&<tr><td colSpan={6} className="no-results">No receipts match your search.</td></tr>}</tbody></table></div>}
function Modal({title,onClose,children,wide=false}:{title:string;onClose:()=>void;children:React.ReactNode;wide?:boolean}){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{const old=document.activeElement as HTMLElement;const panel=ref.current;panel?.focus();const lock=(e:KeyboardEvent)=>{if(e.key!=='Tab'||!panel)return;const items=panel.querySelectorAll<HTMLElement>('button:not(:disabled), a[href], input, select, textarea, summary, [tabindex="0"]');const first=items[0],last=items[items.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===panel)){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}};document.addEventListener('keydown',lock);const overflow=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',lock);document.body.style.overflow=overflow;old?.focus();};},[]);return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><div ref={ref} tabIndex={-1} className={`modal ${wide?'wide':''}`} role="dialog" aria-modal="true" aria-label={title}><div className="modal-header"><h2>{title}</h2><button className="icon-button" onClick={onClose} aria-label="Close dialog"><Icon name="close"/></button></div><div className="modal-body">{children}</div></div></div>}
